# This workflow publishes a docker image on tag push or manual dispatch.

name: Create Docker Image (Release and Staging)

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  # This should allow creation of docker images even in forked repositories
  REPO: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  build:
    if: github.repository == 'funnycups/Luker'
    runs-on: ubuntu-latest

    steps:
      - name: Set lowercase repo name
        run: |
          echo "IMAGE_NAME=${REPO,,}" >> ${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v4.1.2

      # Setting up QEMU for multi-arch image build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for the image
        uses: docker/metadata-action@v5.5.1
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=manual,enable=${{ github.event_name == 'workflow_dispatch' }}

      # Login into package repository as the person who created the release
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build docker image using dockerfile for amd64 and arm64
      # Tag it with branch name
      # Assumes branch name is the version number
      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
